# modifier aliases
alias http='http --style=bw'
alias ls='ls --color=auto'

# shortener aliases
alias g='git'
alias pac='trizen'
alias py='python'
alias xo='xdg-open'

# navigation aliases
alias ...='../..'
alias ....='../../..'
alias .....='../../../..'
alias ......='../../../../..'

# git aliases
alias ga='git add'
alias gaa='git add --all'
alias gbr='git branch'
alias gca='git commit --amend'
alias gcl='git clone'
alias gcm='git commit -m'
alias gcn='git clean'
alias gco='git checkout'
alias gdc='git diff --cached'
alias gdf='git diff'
alias gfe='git fetch'
alias gfl='git reflog'
alias glg='git log'
alias gmr='git merge'
alias gmv='git mv'
alias gp='git push'
alias gpl='git pull'
alias grb='git rebase'
alias grm='git rm'
alias grs='git reset'
alias grv='git revert'
alias gsa='git status --short -uall'
alias gsh='git stash'
alias gss='git status --short'
